### ISSUE TITLE
False Output 

### ISSUE THREAD

**Issue by z3dc0ps** [thewhiteh4t/FinalRecon#38] opened 2021-01-17 07:44 UTC
![a](https://user-images.githubusercontent.com/61974788/104834520-ea70e180-58c5-11eb-80e1-e021ae29321b.PNG)

**Comment by thewhiteh4t** [comment] 2021-01-19 05:14
@z3dc0ps is the output blank everytime you run it?

**Comment by z3dc0ps** [comment] 2021-01-19 07:41
Yes output is blank, I tried multiple times

**Comment by thewhiteh4t** [comment] 2021-01-19 13:14
@z3dc0ps is it happening with every target? because I tested and its working for me

![2021-01-19_18-43](https://user-images.githubusercontent.com/36354846/105039248-539f5300-5a86-11eb-9c1b-7285fec8ad0c.png)

**Comment by z3dc0ps** [comment] 2021-01-22 13:20
@thewhiteh4t  Yes

![a](https://user-images.githubusercontent.com/61974788/105495846-ad9c5480-5ce2-11eb-91f3-0925f667e302.PNG)

**Comment by thewhiteh4t** [comment] 2021-01-22 13:39
this is weird...

**Comment by z3dc0ps** [comment] 2021-01-22 15:01
This is only for port scan , others are working properly

**Comment by thewhiteh4t** [comment] 2022-07-25 00:48
fixed in v1.1.4
![Screenshot_2022-07-25_06-22-58](https://user-images.githubusercontent.com/36354846/180673547-e8ffd1b3-00fd-420e-9db0-ba0ffb5565a3.png)

**Closed by thewhiteh4t** 2022-07-25 00:48 UTC

**Comment by z3dc0ps** [comment] 2022-07-25 06:34
![image](https://user-images.githubusercontent.com/61974788/180712854-a8579bf5-c417-4254-9527-fbf06999da9d.png)


@thewhiteh4t  I am getting the same blank output even in the new version also

**Comment by thewhiteh4t** [comment] 2022-07-25 06:36
@z3dc0ps are you using some proxy or something in the background?

I need to be able to reproduce the issue, so far in my testing this is not happening

**Comment by z3dc0ps** [comment] 2022-07-25 06:42
@thewhiteh4t No I am not using any proxy, as you can see, it shows output for other options.

![image](https://user-images.githubusercontent.com/61974788/180714152-0b81775b-76d8-4c1d-9f2c-7cdae0719b70.png)

![image](https://user-images.githubusercontent.com/61974788/180714290-72c08112-c1f7-4994-9715-5dcc8391f185.png)

**Comment by thewhiteh4t** [comment] 2022-07-25 06:46
@z3dc0ps for past 1 week i was testing and i always get results in port scan 😅

**Comment by z3dc0ps** [comment] 2022-07-25 08:13
For me, the issue was with threads, I added a pull request please check it [here](https://github.com/thewhiteh4t/FinalRecon/pull/54)

**Comment by thewhiteh4t** [comment] 2022-07-25 08:17
@z3dc0ps nice! I saw I will merge later today, how many threads worked for you and what is your system specs?

**Comment by z3dc0ps** [comment] 2022-07-25 08:26
@thewhiteh4t For me, working fine with 85 threads. os is Kali Linux using in VMware.

![image](https://user-images.githubusercontent.com/61974788/180732444-4e185416-4010-43c7-aeaf-78888ad57e13.png)

![image](https://user-images.githubusercontent.com/61974788/180732483-bb5a5f28-a693-4bf1-a3d8-bf188f6fd765.png)

**Comment by thewhiteh4t** [comment] 2022-07-25 08:27
interesting!
