### ISSUE TITLE
unicode decode error [--dir] and json decode error [--sub]

### ISSUE THREAD

**Issue by meetgyn** [thewhiteh4t/FinalRecon#34] opened 2020-12-03 19:18 UTC
root@kali:/opt/tools/finalrecon# python3 finalrecon.py --dir https://xxxx.xxxx.com -e txt,php -w wordlists/dirb_big.txt

![image](https://user-images.githubusercontent.com/3695608/101077136-24d72700-3583-11eb-92f6-b8ce78167a50.png)

**Comment by thewhiteh4t** [comment] 2020-12-03 19:28
@meetgyn thanks for raising this issue, please use `SecLists` wordlists in the mean time, you can find `big.txt` in `SecLists/Discovery/Web-Content/big.txt`

**Comment by meetgyn** [comment] 2020-12-03 22:30
Thank you.
Now another different error is returning to me.
![image](https://user-images.githubusercontent.com/3695608/101096215-029ed280-359e-11eb-8ab1-e87a4c920aaa.png)

**Comment by thewhiteh4t** [comment] 2020-12-03 22:35
@meetgyn is it possible for you to share the target url? I need to reproduce the issue on my end, is it happening with every target?

**Comment by meetgyn** [comment] 2020-12-03 22:47
Strange that it was working perfectly. Now it is giving error on all targets.

https://integratto.com.br

**Comment by thewhiteh4t** [comment] 2020-12-03 22:56
@meetgyn try again after sometime, looks like its a rate limit issue, I will try to reproduce the issue, thanks!

**Comment by thewhiteh4t** [comment] 2020-12-03 22:58
Did you add facebook api key?

**Comment by meetgyn** [comment] 2020-12-03 23:03
Thank you, I will do further tests later.
Yes, I put the Facebook API and Virustotal

**Comment by thewhiteh4t** [comment] 2020-12-03 23:04
Please check the format once and verify if json is not invalid, there are examples in readme for both

**Comment by ratnadip1998** [comment] 2021-06-08 16:58
i am facing same error on --sub any fix for this ?

**Closed** 2022-05-03 21:26 UTC
